all: CSharp
	cd CSharp/AIn && $(MAKE) all
	cd CSharp/AInScan && $(MAKE) all
	cd CSharp/AInScanWithCallback && $(MAKE) all
	cd CSharp/AOut && $(MAKE) all
	cd CSharp/AOutScan && $(MAKE) all
	cd CSharp/CtrIn && $(MAKE) all
	cd CSharp/DIn && $(MAKE) all
	cd CSharp/DOut && $(MAKE) all
	cd CSharp/TempView && $(MAKE) all

install: CSharp
	cd CSharp/AIn && $(MAKE) install
	cd CSharp/AInScan && $(MAKE) install
	cd CSharp/AInScanWithCallback && $(MAKE) install
	cd CSharp/AOut && $(MAKE) install
	cd CSharp/AOutScan && $(MAKE) install
	cd CSharp/CtrIn && $(MAKE) install
	cd CSharp/DIn && $(MAKE) install
	cd CSharp/DOut && $(MAKE) install
	cd CSharp/TempView && $(MAKE) install

uninstall: CSharp
	cd CSharp/AIn && $(MAKE) uninstall
	cd CSharp/AInScan && $(MAKE) uninstall
	cd CSharp/AInScanWithCallback && $(MAKE) uninstall
	cd CSharp/AOut && $(MAKE) uninstall
	cd CSharp/AOutScan && $(MAKE) uninstall
	cd CSharp/CtrIn && $(MAKE) uninstall
	cd CSharp/DIn && $(MAKE) uninstall
	cd CSharp/DOut && $(MAKE) uninstall
	cd CSharp/TempView && $(MAKE) uninstall

